#! /usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/lib";

$| = 1;

use CGI qw( :default );

print CGI::header('text/plain'), "Hello World\n";

foreach my $key (sort keys %ENV) {
    print "$key: $ENV{$key}\n";
}
